### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by edsu** [edsu/etudier#1]
Running etudier on [this](https://scholar.google.com/scholar?cites=12216592182874495788&as_sdt=20000005&sciodt=0,21&hl=en') yields a UnboundLocalError exception after running for a bit:

```
./etudier.py --depth 2 'https://scholar.google.com/scholar?cites=12216592182874495788&as_sdt=20000005&sciodt=0,21&hl=en'
...
https://scholar.google.com/scholar?cites=4696240701634903645&as_sdt=20000005&sciodt=0,21&hl=en
Traceback (most recent call last):
  File "./etudier.py", line 266, in <module>
    main(args.url, output=args.output, depth=args.depth, pages=args.pages)
  File "./etudier.py", line 20, in main
    for from_pub, to_pub in get_citations(url, depth=depth, pages=pages):
  File "./etudier.py", line 91, in get_citations
    pages=pages
  File "./etudier.py", line 91, in get_citations
    pages=pages
  File "./etudier.py", line 76, in get_citations
    'id': article_id,
UnboundLocalError: local variable 'article_id' referenced before assignment
```

**Comment by shawngraham** [comment]
yep, that's what i was getting. weird, eh?

**Comment by edsu** [comment]
Ok, v0.0.2 was just released which should have a fix for this. See [21ecfc3] for the details.
