### ISSUE TITLE
Error in running etudier

### ISSUE THREAD

**Issue by hh1985** [edsu/etudier#15]
Hi,

I tried to run the example and receive errors:
```
$ etudier 'https://scholar.google.com/scholar?hl=en&as_sdt=0%2C21&q=cscw+memory&btnG='
Traceback (most recent call last):
  File "/Users/hanh/miniconda3/bin/etudier", line 8, in <module>
    sys.exit(main())
  File "/Users/hanh/miniconda3/lib/python3.7/site-packages/etudier.py", line 31, in main
    driver = webdriver.Chrome()
  File "/Users/hanh/miniconda3/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/hanh/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/hanh/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/hanh/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/hanh/miniconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81
```

It seems there is problem with ChromeDriver version 

-Han

**Comment by hh1985** [comment]
I downloaded the ChromeDriver manually from https://chromedriver.chromium.org/downloads and solved the version problem.
