### ISSUE TITLE
Cannot scrape keyword search results

### ISSUE THREAD

**Issue by mohamad-h-alizade** [edsu/etudier#29]
Although working fine with citations, when I use it for keyword search results it returns empty graphs.

Traceback (most recent call last):
  File "/home/username/.local/bin/etudier", line 8, in <module>
    sys.exit(main())
  File "/home/aliz/username/lib/python3.9/site-packages/etudier/__init__.py", line 54, in main
    write_output(g, args)
  File "/home/username/.local/lib/python3.9/site-packages/etudier/__init__.py", line 264, in write_output
    cluster_nodes(g)
  File "/home/username/.local/lib/python3.9/site-packages/etudier/__init__.py", line 90, in cluster_nodes
    for i, comm in enumerate(greedy_modularity_communities(undirected_g)):
  File "/home/username/anaconda3/lib/python3.9/site-packages/networkx/algorithms/community/modularity_max.py", line 352, in greedy_modularity_communities
    communities = next(community_gen)
  File "/home/username/anaconda3/lib/python3.9/site-packages/networkx/algorithms/community/modularity_max.py", line 79, in _greedy_modularity_communities_generator
    q0 = 1 / m
ZeroDivisionError: division by zero

**Comment by edsu** [comment]
How are you running it?
