### ISSUE TITLE
search

### ISSUE THREAD

**Issue by shawngraham** [edsu/etudier#5]
tried the search function, as per the readme:

```
etudier.py 'https://scholar.google.com/scholar?hl=en&as_sdt=0%2C21&q=cscw+memory&btnG='
```

result:

```https://scholar.google.com/scholar?hl=en&as_sdt=0%2C21&q=cscw+memory&btnG=
Traceback (most recent call last):
  File "/usr/local/bin/etudier.py", line 266, in <module>
    main(args.url, output=args.output, depth=args.depth, pages=args.pages)
  File "/usr/local/bin/etudier.py", line 22, in main
    g.add_node(to_pub['id'], label=to_pub['title'], **remove_nones(to_pub))
TypeError: 'NoneType' object is not subscriptable```

**Comment by edsu** [comment]
This also works for me, at least with v0.0.4. Are you sure you have v0.0.4 installed?

    pip3 list | grep etudier

**Comment by edsu** [comment]
🙏
